let shopItemData = [
    {
      id: "a01",
      name: "Toddler Set",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy1.jpg",
    },
    {
      id: "a02",
      name: "Doll family house",
      price: 35,
      desc: "Sylvanian Families Nukkekoti Red Roof Cosy Cottage",
      img: "./images/toy4.jpg",
    },
    {
      id: "a03",
      name: "Baby First Rider",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy3.jpeg",
    },
    {
      id: "a04",
      name: "Teddy Bear",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy3a.jpg",
    },
    {
      id: "a05",
      name: "Toys set for toddler",
      price: 30,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy5.jpg",
    },
    {
      id: "a06",
      name: "Robot",
      price: 40,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy6.jpg",
    },
    {
      id: "a06",
      name: "Lego",
      price: 35,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy7.jpg",
    },
    {
      id: "a08",
      name: "Block Train",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy8.jpg",
    },
    {
      id: "a09",
      name: "Brio Train",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy9.jpg",
    },
    {
      id: "a10",
      name: "Barbie Ambulance",
      price: 30,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy10.jpg",
    },
    {
      id: "a11",
      name: "Transformer",
      price: 55,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy11.jpg",
    },
    {
      id: "a12",
      name: "RC-monsteriauto",
      price: 60,
      desc: "RC-monsteriauto Hot Wheels Rhinomite.",
      img: "./images/toy12.jpg",
    },
    {
      id: "a13",
      name: "Kitchen",
      price: 90,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy13.jpg",
    },
    {
      id: "a14",
      name: "Reborn Baby Doll",
      price: 75,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy14.jpg",
    },
    {
      id: "a15",
      name: "Blaster Guns",
      price: 55,
      desc: "2 Pack Blaster Guns Toy Guns for Boys with 60 Pack Refill Soft ",
      img: "./images/toy15.jpg",
    },
    {
      id: "a16",
      name: "Paloauto valo- ja äänitoiminnoilla",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "./images/toy16.jpg",
    },
  ];